projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: http://157.245.80.78:4466
  prisma:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: prisma/prisma.yml
